### ISSUE TITLE
About dark theme, there be a whitespace blank on footer of page.

### ISSUE THREAD

**Issue by loveminimal** [geekplux/hexo-theme-typing#29]
When I set the theme as **dark** ,  to me, there is a problem.

On the footer of a post page, there be two whitespace black. I have tried to clear all caches and updates, but it still exist. Do you met it? And if you can give me a help, thank you.

**Comment by geekplux** [comment]
could you please provide more details? like captures

**Comment by loveminimal** [comment]
> could you please provide more details? like captures

Okay, hah..., like this,
![issue](https://user-images.githubusercontent.com/23427211/46985815-e53cef00-d11e-11e8-816c-b13c7054ce32.png)

**Comment by geekplux** [comment]
got it, I will fix it later, thanks

**Comment by loveminimal** [comment]
> got it, I will fix it later, thanks

Thanks again. A simple blog, need nothing extra, is perfect. And your theme is my favorite. Waiting for your updating.

**Comment by curbengh** [comment]
I also have this issue in my blog. I fixed this by removing `background:#fff` from `html{}` class from [typing.css](https://github.com/geekplux/hexo-theme-typing/blob/master/source/css/typing.css).
Those values are not necessary since `body{}` already set font and background colours.

The values are added [typo.css](https://github.com/sofish/typo.css/blob/master/typo.css#L6).

Speaking of css, I suggest normalize.css and autoprefixer to be updated to support newer versions of browser.

Edit: Created a PR https://github.com/geekplux/hexo-theme-typing/pull/31 to fix this.

**Comment by geekplux** [comment]
thank you nice guys.
