### ISSUE TITLE
Question about the CSS styling

### ISSUE THREAD

**Issue by blokchoy** [geekplux/hexo-theme-typing#5]
Hi! Love your theme, it's elegant and beautiful. I was going through your source files for the theme, and have been trying to change the default font for the main page. I'm still very new at hexo and general web-design, but changing the font families don't seem to be working for me. In the 'typing' css style sheet, where should I be changing to change fonts?

Thanks so much!

**Comment by geekplux** [comment]
Glad to hear you using it, thanks.

You can set font-families in `source.css` instead of changing `typing.css` directly.
run `make css` to build the `source.css` to `typing.css` after you edited it.

reference:

- https://github.com/geekplux/hexo-theme-typing/blob/master/makefile
- https://github.com/geekplux/hexo-theme-typing#development

**Comment by blokchoy** [comment]
thanks!!
